"""Various tools using accompy."""

from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional, Union, Sequence

from .base import Score


def generate_mma_wav(
    score: Score,
    output_path: Union[str, Path],
    *,
    groove: str = "Swing",
    tempo: int = 120,
    repeats: int = 1,
) -> Path:
    """Generate a WAV file from a Score using an MMA groove.

    Unlike :func:`accompy.generate_accompaniment`, this function lets you
    specify an **arbitrary MMA groove name** (e.g. ``"Bebop"``,
    ``"GypsyJazz"``, ``"NiteJazz"``), not just the eight built-in style
    keywords.

    Args:
        score: A :class:`Score` with chord measures.
        output_path: Destination WAV file path.
        groove: MMA groove name (case-sensitive).  Run ``mma -Dg`` to see
            available grooves.
        tempo: Tempo in BPM.
        repeats: Number of times to repeat the progression.

    Returns:
        Path to the generated WAV file.

    Raises:
        RuntimeError: If MMA is not installed or the groove is invalid.

    Example::

        >>> from accompy import Score, generate_mma_wav
        >>> score = Score.from_string("| Dm7 | G7 | C^7 |")
        >>> generate_mma_wav(score, "/tmp/test.wav", groove="BossaNova", tempo=140)  # doctest: +SKIP
        PosixPath('/tmp/test.wav')
    """
    from .main import _find_mma, _ensure_mma_grooves, _ireal_chord_to_mma
    from .synthesis.fluidsynth import FluidSynthBackend

    _ensure_mma_grooves()
    mma_cmd = _find_mma()

    # Build MMA content
    lines = [
        f"// Generated by accompy",
        f"// {score.title}",
        f"Tempo {tempo}",
        f"Groove {groove}",
        "",
    ]
    bar_num = 1
    for _ in range(max(1, repeats)):
        for measure in score.measures:
            chords_mma = " ".join(_ireal_chord_to_mma(c) for c in measure)
            lines.append(f"{bar_num} {chords_mma}")
            bar_num += 1

    mma_content = "\n".join(lines)

    # Write MMA file and run MMA → MIDI
    mma_path = Path(tempfile.mktemp(suffix=".mma"))
    midi_path = mma_path.with_suffix(".mid")
    output_path = Path(output_path)

    try:
        mma_path.write_text(mma_content)
        result = subprocess.run(
            [mma_cmd, str(mma_path), "-f", str(midi_path)],
            capture_output=True,
            text=True,
            check=True,
        )
        # Render MIDI → WAV
        backend = FluidSynthBackend()
        backend.render_to_file(midi_path, output_path)
        return output_path
    except subprocess.CalledProcessError as e:
        error_msg = (e.stderr or e.stdout or "").strip()
        raise RuntimeError(f"MMA failed (groove={groove!r}): {error_msg}") from e
    except FileNotFoundError:
        raise RuntimeError(
            "MMA not found. Install from https://www.mellowood.ca/mma/"
        )
    finally:
        mma_path.unlink(missing_ok=True)
        midi_path.unlink(missing_ok=True)


def generate_variations(
    score: Score,
    output_dir: Union[str, Path],
    *,
    keys: Sequence[str] = ("C",),
    tempos: Sequence[int] = (120,),
    grooves: Sequence[str] = ("Swing",),
    repeats: int = 1,
    filename_template: str = "{title}_{key}_{tempo}bpm_{groove}.wav",
) -> list[Path]:
    """Batch-generate WAV files for many key / tempo / groove combinations.

    Produces one WAV for each ``(key, tempo, groove)`` triple (cycled from the
    shortest sequences).  Useful for creating practice backing-track
    collections.

    Args:
        score: Base :class:`Score` (will be transposed per key).
        output_dir: Directory for output files.
        keys: Keys to transpose to.
        tempos: Tempos in BPM to cycle through.
        grooves: MMA groove names to cycle through.
        repeats: Number of repeats per file.
        filename_template: Template for filenames. Placeholders:
            ``{title}``, ``{key}``, ``{tempo}``, ``{groove}``.

    Returns:
        List of Paths to successfully generated files.

    Example::

        >>> from accompy import Score, generate_variations  # doctest: +SKIP
        >>> score = Score.from_string("| C6 | Do | C6/E | Fo |", key="C")
        >>> generate_variations(  # doctest: +SKIP
        ...     score, "/tmp/variations",
        ...     keys=["C", "G", "F"],
        ...     tempos=[100, 120],
        ...     grooves=["Swing", "BossaNova"],
        ... )
    """
    from itertools import cycle as _cycle
    from .util import transpose_score

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build combos by cycling shorter sequences
    n = max(len(keys), len(tempos), len(grooves))
    key_cycle = _cycle(keys)
    tempo_cycle = _cycle(tempos)
    groove_cycle = _cycle(grooves)
    combos = [
        (next(key_cycle), next(tempo_cycle), next(groove_cycle)) for _ in range(n)
    ]

    results: list[Path] = []
    for key, tempo, groove in combos:
        transposed = transpose_score(score, key) if key != score.key else score
        safe_key = key.replace("#", "sharp").replace("b", "flat")
        safe_title = score.title.replace(" ", "_")
        filename = filename_template.format(
            title=safe_title, key=safe_key, tempo=tempo, groove=groove,
        )
        output_path = output_dir / filename
        try:
            generate_mma_wav(
                transposed, output_path, groove=groove, tempo=tempo, repeats=repeats,
            )
            size = os.path.getsize(output_path)
            print(f"  OK: {filename} ({size:,} bytes)")
            results.append(output_path)
        except Exception as e:
            print(f"  FAILED: {filename} - {e}")

    print(f"\nGenerated {len(results)}/{len(combos)} files in {output_dir}")
    return results
